def mypods
  pod 'Fabric'
  pod 'Crashlytics'

  pod 'AWSCore'
  pod 'AWSS3'
  pod 'AWSCognito'

  pod "Lock", :inhibit_warnings => true
  pod "JWTDecode"
  pod "SimpleKeychain"

  pod "NSLogger"

  pod 'GBDeviceInfo', '~> 3.5'
end

target 'Sensorama' do
  mypods
end

target 'SensoramaTests' do
  mypods
end

target 'SensoramaUITests' do
  mypods
end

use_frameworks!
platform :ios, '8.0'
