# Copyright 2016 Wojciech Adam Koszek <wojciech@koszek.com>
#
# Below are the libraries used. Without them, Sensorama wouldn't have
# existed.
#

use_frameworks!
platform :ios, '8.0'

def mypods
  pod 'Fabric'
  pod 'Crashlytics'

  pod 'AWSCore'
  pod 'AWSS3'
  pod 'AWSCognito'

  pod "Lock", :inhibit_warnings => true
  pod "JWTDecode"
  pod "SimpleKeychain"

  pod "NSLogger"

  pod 'GBDeviceInfo', '~> 3.5'
  pod 'BZipCompression', '~> 1.0.0'
  pod "MPMessagePack"
  pod 'JTCalendar', '~> 2.0'

  pod 'InAppSettingsKit'
  pod 'DZNEmptyDataSet'
  pod 'GCNetworkReachability'
  pod 'GroundControl', :git => 'https://github.com/wkoszek/GroundControl.git'

  pod 'FontAwesome+iOS'
  pod 'Whisper'
  pod "Realm"
  pod 'JSONModel'
  pod 'mailgun', :git => 'https://github.com/wkoszek/objc-mailgun'
  pod 'EAIntroView'

end

target 'Sensorama' do
  mypods
  target :SensoramaTests do
    inherit! :search_paths
  end
  target 'SensoramaUITests' do
    inherit! :search_paths
  end
end

