# vim: ai ts=2 sts=2 et sw=2 ft=ruby
fastlane_version "1.52.0"

default_platform :ios

is_ci = ENV['TRAVIS'] ? true : false

platform :ios do

  desc "Installs FixCode which disables the \"Fix Issue\" button in Xcode"
  lane :xcode do
    install_xcode_plugin(
      url: "https://github.com/fastlane/FixCode/releases/download/0.2.0/FixCode.xcplugin.zip"
    )
  end

  desc "Fetches the provisioning profiles so you can build locally and deploy to your device"
  lane :certs do
    slack(message: "certs", success: true)
    match(
      app_identifier: "com.koszek.Sensorama",
      type: "development",
      git_url: ENV['FASTLANE_GIT_URL'],
      force: is_ci ? false : true,
      readonly: is_ci ? true : false
    )
  end

  lane :appmake do
    slack(message: "appmake", success: true)
    produce(
       username: 'wkoszek@freebsd.org',
       app_identifier: 'com.koszek.Sensorama',
       app_name: 'Sensorama',
       language: 'English',
       app_version: '1.0',
       skip_itc: true,
     )
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Deliver to Crashlytics"
  lane :crashlytics_beta do
    crashlytics(
       api_token: ENV['FABRIC_API_KEY'],
       build_secret:  ENV['FABRIC_BUILD_SECRET'],
       groups: 'sensorama-testers'
    )
  end

  desc "This will also make sure the profile is up to date"
  lane :beta do
    certs
    update_app_identifier(
      app_identifier: "com.koszek.Sensorama",
      plist_path: "Sensorama/Info.plist"
    )
    sigh(development: true)
    if not is_ci then
      increment_build_number
      commit_version_bump(xcodeproj: "Sensorama.xcodeproj")
    end
    badge
    gym(
      workspace: "Sensorama.xcworkspace",
      scheme: "Sensorama"
    )
    #scan(scheme: "SensoramaTests", workspace: "Sensorama.xcworkspace")
    #deliver
    crashlytics_beta
    `git checkout ../Sensorama/Assets.xcassets/AppIcon.appiconset/`
    #frameit
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    if not is_ci then
      increment_build_number
      commit_version_bump(xcodeproj: "Sensorama.xcodeproj")
    end
    update_app_identifier(
      app_identifier: "com.koszek.Sensorama.master",
      plist_path: "Sensorama/Info.plist"
    )
    match(
      app_identifier: "com.koszek.Sensorama.master",
      type: "appstore",
      git_url: ENV['FASTLANE_GIT_URL'],
      force: is_ci ? false : true,
      readonly: is_ci ? true : false
    )
    gym(
      workspace: "Sensorama.xcworkspace",
      scheme: "Sensorama"
    )
    deliver(force: true)
  end

  after_all do |lane|
    print "after lane #{lane}"
  end

  error do |lane, exception|
    print "Error happened!"
  end
end
