#!/bin/sh


if [ "$#" -ne 2 ]; then
	echo "iconfinder <name> <param>"
	exit
fi

NAME=$1
P=../Sensorama/Sensorama/Assets.xcassets/${NAME}.imageset/

PARAM=$2
URL=https://www.iconfinder.com/icons/${PARAM}/download/png/512

mkdir -p $P
cp icon.template $P/Contents.json
(
	cd $P
	wget -O _.png $URL
	sips -z 30 30 _.png --out image-1x.png
	sips -z 60 60 _.png --out image-2x.png
	sips -z 90 90 _.png --out image-3x.png
	rm _.png
)
