#!/bin/sh

if [ "$#" -ne 2 ]; then
	echo "iconfinder <name> <param>"
	exit
fi

NAME=$1
P=../Sensorama/Sensorama/Assets.xcassets/${NAME}.imageset/

URL=$2

mkdir -p $P
cp icon.template $P/Contents.json
(
	if [ -e "$URL" ]; then
		cp $URL $P/_.png
	else
		wget -O $P/_.png $URL
	fi

	cd $P

	sips -z 30 30 _.png --out image-1x.png
	sips -z 60 60 _.png --out image-2x.png
	sips -z 90 90 _.png --out image-3x.png

	rm _.png
)
